Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
      - Key: stack
        Value: production
      - Key: Proj
        Value: Nephio
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.0.0/18
      AvailabilityZone: "ap-northeast-2a"
      Tags:
      - Key: stack
        Value: production
      - Key: Proj
        Value: Nephio
  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.64.0/18
      AvailabilityZone: "ap-northeast-2a"
      Tags:
      - Key: stack
        Value: production
      - Key: Proj
        Value: Nephio
  Subnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.128.0/18
      AvailabilityZone: "ap-northeast-2b"
      Tags:
      - Key: stack
        Value: production
      - Key: Proj
        Value: Nephio
  Subnet4:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.192.0/18
      AvailabilityZone: "ap-northeast-2b"
      Tags:
      - Key: stack
        Value: production
      - Key: Proj
        Value: Nephio
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP access via port 80 locked down to the load balancer + SSH access"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      VpcId: !GetAtt VPC.VpcId
      Tags:
      - Key: Proj
        Value: Nephio
  IngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Egress"
      SecurityGroupEgress: 
      - CidrIp: 0.0.0.0/0
        IpProtocol: "-1"
      VpcId: !GetAtt VPC.VpcId
      Tags: 
      - Key: Proj
        Value: Nephio
  # allow local traffic
  # SGBaseIngress:
  #   Type: AWS::EC2::SecurityGroupIngress
  #   Properties:
  #     GroupId: !Ref WebServerSecurityGroup
  #     IpProtocol: '-1'
  #     FromPort: '-1'
  #     ToPort: '-1'
  #     SourceSecurityGroupId: !Ref WebServerSecurityGroup
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      # ImageId: 'ami-0bc4327f3aabf5b71'
      ImageId: 'ami-0bc4327f3aabf5b71'
      InstanceType: 't2.xlarge'
      KeyName: 'ntnguyen'
      SecurityGroupIds:
      - !GetAtt WebServerSecurityGroup.GroupId
      - !GetAtt IngressSecurityGroup.GroupId
      # - 'sg-06d6768a17c6a7c25'
      # - 'sg-095deeaae507aa79e'
      # SubnetId: 'subnet-0634dffba747e46e3'
      SubnetId: !GetAtt Subnet1.SubnetId
      Tags:
      - Key: Proj
        Value: Nephio
Outputs:
  SubnetID:
    Description: Subnet 1
    Value: !Ref Subnet1
  SecurityGreoupID1:
    Description: SSG1
    Value: !Ref WebServerSecurityGroup
  SecurityGreoupID2:
    Description: SSG2
    Value: !Ref IngressSecurityGroup
  WebServerID:
    Description: InstanceId of the first EC2 instance
    Value: !Ref WebServer